# Changes here will be overwritten by Copier
_commit: v0.2.19
_src_path: git+https://gitlab.ewi.tudelft.nl/reit/python-package-template
email: s.wacker@tudelft.nl
environment_manager: uv
full_name: Sören Wacker
host: github.com
license: No license (others may not use, share or modify the code)
min_python_version: '3.10'
org: sdrwacker
project_name: DataXR-Tools
project_short_description: Tools for DataXR
python_name: dataxr_tools
url: git@github.com:CropXR/DataXR-Tools.git
